apiVersion: v1
kind: Service
metadata:
  name: nextweb-service
spec:
  selector:
    app: nextweb
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http # refers to the name of the port in the nextweb deployment.yaml
  type: ClusterIP
