# deploy mimir with the classic architecture
mimir:
  structuredConfig:
    ingest_storage:
      enabled: false # disable ingest storage architecture for now to use classic architecture
    ingester:
      push_grpc_method_enabled: true # required for classic architecture

kafka:
  enabled: false # disable kafka for now which is not required for classic architecture

# use the bundled minio instead of using our own object storage (this is true by default though)
minio:
  enabled: true

# configure each sub-component of mimir
distributor:
  replicas: 1 # specify 1 replica for now

ingester:
  replicas: 3 # to match the default replication factor of 3 (else alloy integration fails with too many unhealthy instances error)
  zoneAwareReplication:
    enabled: false  # disable zone aware ingester replication for local single-zone cluster

querier:
  replicas: 1

queryFrontend:
  replicas: 1

query_scheduler:
  replicas: 1

store_gateway:
  replicas: 1
  zoneAwareReplication:
    enabled: false # disable zone aware store gateway replication for local single-zone cluster

compactor:
  replicas: 1

ruler:
  replicas: 1

alertmanager:
  replicas: 1

rollout_operator:
  enabled: false # disable rollout operator for now which is not required for local single-zone cluster
